apps/Login_Register/urls.py
from django.conf.urls import url, include
# from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'register$', views.register, name='register'),
    url(r'login$', views.login, name='login'),
    url(r'^logout$', views.logout, name='logout')
]

black_belt/urls.py
from django.conf.urls import url,include

urlpatterns = [
    url(r'^', include('apps.Login_Register.urls', namespace = 'login')),
    url('^travel_dashboard', include('apps.travel.urls', namespace = 'travel_dashboard'))
]

apps/Login_Register/models.py
from __future__ import unicode_literals
from django.db import models
import bcrypt
from datetime import datetime
import re

#makes sure name only contains letters and spaces
name_regex = re.compile("^[a-zA-Z\s]+$")

# Create your models here.
class UserManager(models.Manager):
    def register(self, input):
        errors = []

        if len(input['name']) < 3:
            errors.append('Name can not be less than 3 characters')

        if not name_regex.match(input['name']):
            errors.append('Name can contain letters only')

        if len(input['username']) < 3:
            errors.append('Username can not be less than 3 characters')

        if input['password'] != input['confirm']:
            errors.append('Passwords do not match. Try again')

        if len(input['password']) < 8:
            errors.append('Password must be at least 8 characters')

        same = User.objects.filter(username=input['username'])
        if same:
            errors.append('Username is already in use')

        if not input['hire_date']:
            errors.append('Please enter the birthday')
        else:
            date = datetime.strptime(input['hire_date'], "%Y-%m-%d")
            if datetime.today() <= date:
                errors.append('birthday cannot be after today')

        if len(errors) == 0:
            pwHash = bcrypt.hashpw(input['password'].encode(), bcrypt.gensalt().encode())
            user = User.objects.create(name=input['name'], username=input['username'], hire_date=input['hire_date'], password=pwHash)
            return (True, user)

        else:
            return (False, errors)

    def login(self, input):
        errors = []
        user = User.objects.filter(username=input['username'])
        if user.exists():
            InputPw = input['password'].encode()
            HashPw = user[0].password.encode()

            if bcrypt.checkpw(InputPw, HashPw):
                return (True, user[0])
            else:
                errors.append(("Username and password match does not exist!"))
        else:
            errors.append(("Username and password match does not exist!"))
        return (False, errors)

class User(models.Model):
    name = models.CharField(max_length=255)
    username = models.CharField(max_length=255)
    password = models.CharField(max_length=100)
    hire_date = models.DateField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = UserManager()

apps/Login_Register/views.py
from django.shortcuts import render, redirect
from .models import User
from django.contrib import messages
from django.core.urlresolvers import reverse

# Create your views here.
def index(request):
    if 'user_id' in request.session:
        return redirect(reverse('travel_dashboard:index'))
    else:
        return render(request, 'Login_Register/index.html')

def register(request):
    result = User.objects.register(request.POST)
    if result[0] == True:
        request.session['user_id'] = result[1].id
        messages.success(request, "Hello! You have successfully registered! Now please log in.")
        return redirect(reverse('login:index'))
    else:
        for error in result[1]:
            messages.error(request, error)
        return redirect(reverse('login:index'))

def login(request):
    result = User.objects.login(request.POST)
    if result[0] == True:
        request.session['user_id'] = result[1].id
        return redirect(reverse('travel_dashboard:index'))
    else:
        for error in result[1]:
            messages.error(request, error)
        return redirect(reverse('login:index'))

def logout(request):
    if 'user_id' in request.session:
        del request.session['user_id']
        messages.success(request, "You have been successfully logged out")
        return redirect(reverse('login:index'))

apps/Login_Register/templates/Login_Register/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Login and Registration</title>
    <meta charset="utf-8">
    <link href='http://fonts.googleapis.com/css?family=Titillium+Web:400,300,600' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">
  <script type="text/javascript" charset="utf-8"></script>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'Login_Register/css/style.css' %}">
</head>
<body>

    <div class="form">
      <div id="message">
        {% if messages %}
            {% for message in messages %}
                <li>{{message}}</li>
            {% endfor %}
        {% endif %}
      </div>

        <div class="tab-content">
          <div id="signup">

          <form class="ui form" action="{% url 'login:register' %}" method="post">
          {% csrf_token %}
          <div class="top-row">
            <div class="field-wrap">

              <input type="text" required autocomplete="off" name="name" placeholder="Name">
            </div>
          </div>
          <input type="text" name="username" placeholder="Username">
          <input type="password" name="password" placeholder="Password">
          <input type="password" name="confirm" placeholder="Confirm Password">
          <span class='bob'>Birthday:<span> <input type="date" name="hire_date" placeholder="Confirm Password">
          <input type="submit" value="Register" class="button button-block">
        </form>
      </div>

      <div class="login">

        <form class="ui form" action="{% url 'login:login' %}" method="post">
          {% csrf_token %}
          <div class="field-wrap">
            <input type="text" name="username" placeholder="Username">
          </div>

          <div class="field-wrap">
            <input type="password" name="password" placeholder="Password">
          </div>

          <input type="submit" value="Login" class="button button-block">

        </form>

        </div>

      </div>
    </div>
      <script src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>

        <script src="js/index.js"></script>
</body>
</html>