apps/travel/urls.py
from django.conf.urls import url, include
# from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^add_travel_plan$', views.showAdd, name = 'add_page'),
    url(r'^add_travel_plan/add$', views.addPlan, name = 'add_plan'),
    url(r'^view_plan/(?P<id>\d+)$', views.viewPlan, name = 'view_plan'),
    url(r'^join/(?P<id>\d+)$', views.join, name = 'join'),
    url(r'^logout/(?P<id>\d+)$', views.logout, name='logout'),

]

black_belt/urls.py
from django.conf.urls import url,include

urlpatterns = [
    url(r'^', include('apps.Login_Register.urls', namespace = 'login')),
    url('^travel_dashboard', include('apps.travel.urls', namespace = 'travel_dashboard'))
]

apps/travel/models.py
from __future__ import unicode_literals
import re
from datetime import date, datetime
from django.db import models
from ..Login_Register.models import User

class TripManager(models.Manager):
    def validTravelDate(self, date):
        today = datetime.strptime(str(date.today())[:10], '%Y-%m-%d')
        difference = (date - today).days
        if difference <= 0:
            return False
        else:
            return True
    def validDates(self, depDate, arrDate):
        difference = (arrDate - depDate).days
        if difference <= 0:
            return False
        else:
            return True

class Trip(models.Model):
    destination = models.CharField(max_length = 100)
    startDate = models.DateField()
    endDate = models.DateField()
    plan = models.CharField(max_length = 1000)
    users = models.ForeignKey(User, related_name = 'users_on_trip')
    objects = TripManager()

class UserAndTrip(models.Model):
    users = models.ForeignKey(User, related_name = 'user_going')
    trips = models.ForeignKey(Trip, related_name = 'trip_going')

apps/travel/views.py
from django.shortcuts import render, redirect
from .models import Trip, UserAndTrip
from ..Login_Register.models import User
from django.contrib import messages
from datetime import datetime
from django.core.urlresolvers import reverse
# Create your views here.

def index(request):
    if 'user_id' in request.session:
        user = User.objects.get(id = request.session['user_id'])
        context = {
            'data' : user,
            'user': User.objects.get(id = request.session['user_id']),
            'trips': UserAndTrip.objects.filter(users = user),
            'all_trips': Trip.objects.all().exclude(users = request.session['user_id']),
            'messages': messages.get_messages(request)
        }
        return render(request, 'travel/index.html', context)
    else:
        return redirect(reverse('login:index'))

def showAdd(request):
    context = {
    'messages': messages.get_messages(request)
    }
    return render(request, 'travel/add.html', context)

def viewPlan(request, id):
    trip = Trip.objects.get(id = id)
    user = User.objects.get(id = request.session['user_id'])
    context = {
    'trip': trip,
    'trips': UserAndTrip.objects.filter(trips = trip).exclude(users = user)
    }
    return render(request, 'travel/plan.html', context)

def join(request, id):
    user = User.objects.get(id = request.session['user_id'])
    trip = Trip.objects.get(id = id)
    check = UserAndTrip.objects.filter(users = user).filter(trips = trip)
    if not check:
        UserAndTrip.objects.create(users = user, trips = trip)
    else:
        messages.error(request, "You're already going on this trip silly")
    return redirect(reverse('travel_dashboard:index'))

def addPlan(request):
    if request.method == 'POST':
        flag = True
        destination = request.POST['destination']
        plan = request.POST['plan']
        depDate = datetime.strptime(str(request.POST['depDate'])[:10], '%Y-%m-%d')
        arrDate = datetime.strptime(str(request.POST['arrDate'])[:10], '%Y-%m-%d')
        user = User.objects.get(id = request.session['user_id'])
        if not Trip.objects.validTravelDate(depDate):
            flag = False
            messages.error(request, 'Sorry, the departure date must be a date in the future')
        if not Trip.objects.validDates(depDate, arrDate):
            flag = False
            messages.error(request, 'Sorry, the arrival date must be after the departure date')
        if flag:
            trip = Trip.objects.create(destination = destination, plan = plan, startDate = depDate, endDate = arrDate, users = user)
            UserAndTrip.objects.create(users = user, trips = trip)
            return redirect(reverse('travel_dashboard:index'))
    return redirect(reverse('travel_dashboard:add_page'))

def logout(request):
    if 'user_id' in request.session:
        del request.session['user_id']
        messages.success(request, "You have been successfully logged out")
        return redirect(reverse('login:login'))

apps/travel/templates/Travel/add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Add Travel Plan</title>
    <style type="text/css">
    div{
      color: #1ab188;
      width: 500px;
      height: 300;
      border: 10px solid black;
      margin: auto;
      padding: 25px;
      background:rgba(19, 35, 47, 0.9);}
    .message{color: red; }
    a{
      color: white; }
    body{
          background: #c1bdba;
    }
    </style>
</head>
<body>
  <div>
    <a href="{% url 'travel_dashboard:index' %}">Home</a>
    <a href="{% url 'login:logout' %}">Log Out</a>
    <h1>Add a Trip</h1>
    <span class='message'>
    {% if messages %}
    {% for message in messages %}
    <p>{{message}}</p>
    {% endfor %}
    {% endif %}
  </span>
        <form action="{% url 'travel_dashboard:add_plan' %}" method='post'>
        {% csrf_token %}
        <p>Destination: <input type="text" name='destination' required></p>
        <p>Description: <textarea name="plan" rows="5" cols="60" required></textarea></p>
        <p>Departure Date: <input type="date" name='depDate' value={{today}}></p>
        <p>Arrival Date: <input type="date" name='arrDate' value={{today}}></p>
        <input type="submit" value='Add Plan'>

        </form>
    </div>
</body>
</html>

apps/travel/templates/Travel/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Travel Dashboard</title>

    <style type="text/css">
.tg  {border-collapse:collapse;border-spacing:0;}
.tg td{font-family:Arial, sans-serif;font-size:14px;padding:10px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;}
.tg th{font-family:Arial, sans-serif;font-size:14px;font-weight:normal;padding:10px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;}
.tg .tg-6uc3{font-weight:bold;background-color:#000000;color:#ffffff;vertical-align:top}
.tg .tg-yw4l{vertical-align:top;}
body{
margin: auto;
border: 2px white solid;}
/*________________________________*/
div {
  width: 500px;
  height: 300;
  border: 10px solid black;
  margin: auto;
  padding: 25px;
  color: #1ab188;
  background:rgba(19, 35, 47, 0.9);}
/*________________________________*/
  .message{color: red; }
/*________________________________*/
  a{color: white; }
/*________________________________*/
  body{background: #c1bdba;}
/*________________________________*/
#button {
  margin-left: 350px;
}
/*________________________________*/
#add{margin-left: 350px;
text-shadow: }
</style>

</head>
<body>
  <div>
    <a id ='button' href="/logout"><button>Log Out</button></a>
    <h1>Hello {{data.name}}!</h1>
    {% if messages %}
    {% for message in messages %}
    <p>{{message}}</p>
    {% endfor %}
    {% endif %}
    <h2>Your Trip Schedules</h2>
    <table class="tg">

  <tr>
    <th class="tg-6uc3">Destination</th>
    <th class="tg-6uc3">Start Date</th>
    <th class="tg-6uc3">End Date</th>
    <th class="tg-6uc3">Plan</th>
  </tr>
  {% for trip in trips %}
  <tr>
    <td class="tg-yw4l"><a href="{% url 'travel_dashboard:view_plan' id=trip.trips.id %}">{{trip.trips.destination}}</a></td>
    <td class="tg-yw4l">{{trip.trips.startDate}}</td>
    <td class="tg-yw4l">{{trip.trips.endDate}}</td>
    <td class="tg-yw4l">{{trip.trips.plan}}</td>
  </tr>
  {% endfor %}
  </table>

<h1>Other User's Travel Plans</h1>
  <table class="tg">
    <tr>
        <th class="tg-6uc3">User Name</th>
        <th class="tg-6uc3">Destination</th>
        <th class="tg-6uc3">Start Date</th>
        <th class="tg-6uc3">End Date</th>
        <th class="tg-6uc3">Join?</th>
    </tr>
  {% for trip in all_trips %}
  <tr>
      <td class="tg-yw4l">{{trip.users.name}}</td>
      <td class="tg-yw4l"><a href="{% url 'travel_dashboard:view_plan' id=trip.id %}">{{trip.destination}}</a></td>
      <td class="tg-yw4l">{{trip.startDate}}</td>
      <td class="tg-yw4l">{{trip.endDate}}</td>
      <td class="tg-yw4l"><a href="{% url 'travel_dashboard:join' id=trip.id %}">Join</a></td>
  </tr>
  {% endfor %}
</div>
</table>
<a id="add" href="{% url 'travel_dashboard:add_page' %}">Add Travel Plan</a>


</body>
</html>

apps/travel/templates/Travel/plan.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>View Trip Plan</title>
    <style type= 'text/css'>
    div{
      color: #1ab188;
      width: 500px;
      height: 300;
      border: 10px solid black;
      margin: auto;
      padding: 25px;
      background:rgba(19, 35, 47, 0.9);}
    .message{color: red; }
    a{
      color: white; }
    body{
          background: #c1bdba;
    }
    </style>
</head>
<body>
  <div>
    <a href="{% url 'travel_dashboard:index' %}">Home</a>
    <a href="{% url 'login:logout' %}">Log Out</a>


    <h1>{{trip.destination}}</h1>
    <p>Planned By: {{trip.users.name}}</p>
    <p>Description: {{trip.plan}}</p>
    <p>Start Date: {{trip.startDate}}</p>
    <p>End Date: {{trip.endDate}}</p>

    <h1>Other Users Joining the trip</h1>
    {% for trip in trips %}
    <p>{{trip.users.name}}</p>
    {% endfor %}
  </div>
</body>
</html>